tmr_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  # Add these lines if they are missing or named differently
  tip_link: flange
  base_link: base